version: '2.4'
services:
  haproxy-02:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    user: root
    ports:
      - 443:443
      - 80:80
      - 9000:9000
      - 6443:6443
      - 22623:22623
    volumes:
      - type: bind
        source: /glusterfs/vols/haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
      - type: bind
        source: /glusterfs/vols/haproxy/certs
        target: /usr/local/etc/haproxy/certs
        read_only: true
    networks:
      vlan10:
        ipv4_address: 192.168.10.40
  nginx-01:
    image: nginx:latest
    container_name: nginx-01
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: /zfs_master/docker/data/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/templates
        target: /etc/nginx/templates
        read_only: true
      - type: bind
        source: /glusterfs/vols/share
        target: /etc/nginx/html/share
        read_only: true
    networks:
      vlan10:
        ipv4_address: 192.168.10.81
        
  nginx-02:
    image: nginx:latest
    container_name: nginx-02
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: /zfs_master/docker/data/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: /zfs_master/docker/data/nginx/templates
        target: /etc/nginx/templates
        read_only: true
      - type: bind
        source: /glusterfs/vols/share
        target: /etc/nginx/html/share
        read_only: true
    networks:
      vlan10:
        ipv4_address: 192.168.10.82
        
networks:
  vlan10:
    name: vlan10
    driver: macvlan
    driver_opts:
      parent: bridge10
    ipam:
      config:
        - subnet: "192.168.10.0/24"
          ip_range: "192.168.10.1/24"
          gateway: "192.168.10.1"
