version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: unless-stopped
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=${ES_CLUSTER_NAME:?err}
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
      - path.repo=/snapshot_repository
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /zfs_master/docker/data/es01
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /glusterfs/vols/share/es79-repository
        target: /snapshot_repository
    ports:
      - 9200:9200
    networks:
      vlan10:
        ipv4_address: 192.168.10.87
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: unless-stopped
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=${ES_CLUSTER_NAME:?err}
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
      - path.repo=/snapshot_repository
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /zfs_master/docker/data/es02
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /glusterfs/vols/share/es79-repository
        target: /snapshot_repository
    networks:
      vlan10:
        ipv4_address: 192.168.10.88
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: unless-stopped
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=${ES_CLUSTER_NAME:?err}
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
      - path.repo=/snapshot_repository
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /zfs_master/docker/data/es03
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /glusterfs/vols/share/es79-repository
        target: /snapshot_repository
    networks:
      vlan10:
        ipv4_address: 192.168.10.89

networks:
  vlan10:
    external: true
