version: '3'
services:
  sftp:
    image: atmoz/sftp
    ports:
      - 2222:22
    command: ${SFTP_USERNAME:?err}:${SFTP_PASSWORD:?err}:1001
    volumes:
      - type: bind
        source: /zfs_master/share
        target: /home/${SFTP_USERNAME:?err}/share
        read_only: true
    networks:
      vlan10:
        ipv4_address: "192.168.10.91"
    
networks:
  vlan10:
    external: true
