version: "3.7"
services:
  spark-master:
    image: prospecta/bitnami-spark-livy:3.2.1
    restart: unless-stopped
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "8998:8998"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.95"
  spark-worker-1:
    image: bitnami/spark:3.2.1
    restart: unless-stopped
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.96"
  spark-worker-2:
    image: bitnami/spark:3.2.1
    restart: unless-stopped
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.97"
networks:
  vlan10:
    external: true
