version: "3.3"
services:
  spark-master:
    image: prospecta/spark-livy
    restart: unless-stopped
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "8998:8998"
      - "7077:7077"
      - "6066:6066"
    volumes:
      - type: bind
        source: /glusterfs/vols/share/spark
        target: /opt/share
    networks: 
      vlan10:
        ipv4_address: "192.168.10.106"
  spark-worker-01:
    image: prospecta/spark-livy
    restart: unless-stopped
    container_name: spark-worker-01
    hostname: spark-worker-01
    ports:
      - "8081:8081"
    environment:   
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - type: bind
        source: /glusterfs/vols/share/spark
        target: /opt/share
    networks: 
      vlan10:
        ipv4_address: "192.168.10.92"
  spark-worker-02:
    image: prospecta/spark-livy
    restart: unless-stopped
    container_name: spark-worker-02
    hostname: spark-worker-02
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - type: bind
        source: /glusterfs/vols/share/spark
        target: /opt/share
    networks: 
      vlan10:
        ipv4_address: "192.168.10.93"
networks:
  vlan10:
    external: true 
