version: "3.3"
services:
  spark-master:
    image: prospecta/bitnami-spark-livy:3.2.1
    restart: unless-stopped
    container_name: spark-master1
    hostname: spark-master1
    ports:
      - "8080:8080"
      - "8998:8998"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.91"
  spark-worker-1:
    image: bitnami/spark:3.2.1
    restart: unless-stopped
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.92"
  spark-worker-2:
    image: bitnami/spark:3.2.1
    restart: unless-stopped
    container_name: spark-worker2
    hostname: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    networks: 
      vlan10:
        ipv4_address: "192.168.10.93"
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: unless-stopped
    hostname: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks: 
      vlan10:
        ipv4_address: "192.168.10.98"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: unless-stopped
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks: 
      vlan10:
        ipv4_address: "192.168.10.99"  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: unless-stopped
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks: 
      vlan10:
        ipv4_address: "192.168.10.100"
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    hostname: historyserver
    restart: unless-stopped
    volumes:
      - type: bind
        source: /zfs_master/share/spark
        target: /user/hadoop/sync
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks: 
      vlan10:
        ipv4_address: "192.168.10.101"  
networks:
  vlan10:
    external: true
