version: '3'
services:
  postgres14:
    restart: unless-stopped
    image: postgres:14
    container_name: postgres14
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    volumes:
      - type: bind
        source: /zfs_master/docker/data/postgres14
        target: /var/lib/postgresql/data
      - type: bind
        source: /glusterfs/vols/share
        target: /glusterfs/share
        read_only: true
    networks:
      vlan10:
        ipv4_address: "192.168.10.43"
        
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?err}
    ports:
      - "5050:80"
    networks:
      vlan10:
        ipv4_address: "192.168.10.44"
        
networks:
  vlan10:
    external: true
